### PR TITLE
Minor improvements

### PR DESCRIPTION
**Pull request by ziogaschr**
Hello @yankodimitrov. Here are all the changes I had todo so as this excellent lib works with an app we have released at Apple Store. I think all the below changes will/can help other developers integrate your lib based on their needs.

Please take a look, and let me know if you want me to change something or you need me to explain anything.

p.s: Sorry for having merged the #8 in this branch, but it helped me using it in our project. I can remove this commit from the branch if you think so.

Cheers,
Chris

### CODE REVIEW

**Comment by velikanov** [comment]
:+1:

**Comment by yankodimitrov** [comment]
:+1:

**Comment by yankodimitrov** [comment]
Merged in #34

**Comment by ziogaschr** [comment]
Thanks @yankodimitrov. Let's see how can we add some more PR's that have been added to @velikanov repo

**Pull request merged**
