### PR TITLE
Add cocoapod support

### PR DESCRIPTION
**Pull request by ziogaschr**

### CODE REVIEW

**Comment by Lawgrin** [comment]
What is the pod call for this? as pod 'PasscodeLock' doesn't work

**Comment by ziogaschr** [comment]
As this PR hasn't been merged, you can use this:
`pod 'PasscodeLock', :git => 'https://github.com/ziogaschr/SwiftPasscodeLock.git', :branch => 'cocoapods-swift2'`

or the following one that also has some more improvements:
`pod 'PasscodeLock', :git => 'https://github.com/ziogaschr/SwiftPasscodeLock.git', :branch => 'minor-improvements'`

**Comment by Lawgrin** [comment]
Neither of those work and i am running the latest cocoapods. the verbose doesnt even find the pod in the podfile

**Comment by ziogaschr** [comment]
Have you added this `use_frameworks!` on top of the podfile?

**Comment by Lawgrin** [comment]
Yes i do have that in

**Comment by velikanov** [comment]
@ziogaschr thank you very much for this PR!
@Lawgrin it works like a charm for me
@yankodimitrov this PR is probably needs to be merged

**Comment by ziogaschr** [comment]
@velikanov I am  glad I helped.

`minor-improvements` has more stuff in it than just the cocoapod ;)

**Comment by yankodimitrov** [comment]
Thanks! :+1:

**Pull request merged**
