### PR TITLE
Add Cocoapods support

### PR DESCRIPTION
**Pull request by ziogaschr**
Hello @yankodimitrov. Thanks for the great work you've done so far in this lib.

I have added cocoapods support. 
I left your PasscodeKeychainRepository and PasscodeNSUserDefaultsRepository out, as I think that there is no need for someone to load them both in his code and this will be different for each app.

I was thinking that you might want to create a second pod, like SwiftPasscodeLockFull, that will include them. Which I don't really like as an idea.

Also I have added support for overwriting `PasscodeLock.strings` and/or `PasscodeView.xib` in your app. So as dev can easily change things without worrying about broken library updates using cocoapods.

Please check everything in .podspec, like version and license.

### CODE REVIEW

**Comment by yankodimitrov** [comment]
Thank you for your contributions. I will close this pull request for now as Im thinking of rewriting the whole thing for Swift 2.0. It can be implemented in a more clean way. You are right about the passcode repository implementations, those should be out of the dynamic framework.

As for your comment on the `passcode` computed property I believe It was internal property used for testing purposes.

Thanks!

**Comment by ziogaschr** [comment]
I will add 2 new PR today. Basically, it is for adding Passcode expiry time. For example, user can set that the PasscodeLockPresenter will not be engaged for the next 2 minutes after closing the app.

Have you started working on something already?

**Comment by yankodimitrov** [comment]
I will merge your pull request but will not publish the project to CocoaPods yet.

I have started thinking about an alternative implementation. Maybe we can use a separate `UIWindow` which will be on top of the status bar level to fix #2. We can also send notifications on the `NSNotification` center when the passcode lock is presented and dismissed. 

Thanks!

**Comment by ziogaschr** [comment]
I will turn the passcode into a private variable in my next PR about time expiry as you merged this one.
I was thinking the same for `NSNotification` center, but I wasn't sure if you like the idea.

I am not sure if a separate `UIWindow` will fix issue #2. But indeed, it might work and worths trying it.

So will you change more things in the library or just that. As I plan to use it soon in a production app.

Thanks!

**Comment by yankodimitrov** [comment]
Yes, Im thinking of rewriting the whole project. Probably today or tomorrow.

**Comment by ziogaschr** [comment]
I would like some more methods to be public. For example it makes sense to have: `PasscodeLockPresenter.passcodeViewController` and `PasscodeLockPresenter.isPasscodePresented` public. The reason for the former is that the one PR that I will add has to do with turning the Touch ID into a button and present the dialog upon user pressing it. On top of that the implementor can disable Touch ID if for some reason he don't want this.

So, turing the `PasscodeLockPresenter.passcodeViewController` into public will allow the developer to change the Touch ID configuration on runtime based on user settings or other app decisions.

Sorry for adding this comment here as it talks for a different topic than this PR.

**Pull request merged**
